Idmcu: 3
Namespace: "read_imu"
Port: "/dev/ttyACM0"
generate_library_Path: "arduino/libraries"
Baudrate: 57600
Setup_Publisher:  [         [1,"Imu_arduino","sensor_msgs/Imu.msg"]         ]
Setup_Subscriber: [         ]
Setup_Srv_client: [         ]

